github: [kokzyy]
patreon: [kokzyy]
open_collective: [kokzyy]
ko_fi: # [kokzyy]
tidelift: [kokzyy]
community_bridge: [kokzyy]
liberapay: [kokzyy]
issuehunt: [kokzyy]
otechie: [kokzyy]
lfx_crowdfunding: [kokzyy]
custom: ['https://github.com/kokzyy/Valorant-Checker']
